test:
  name: Bigtian1
spring:
  application:
    name: cloud-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///mp?serverTimezone=Asia/Shanghai